name: aes256_demo
description: A demo Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  aes256:
    path: ../
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
